# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://ashz.xyz'
baseurl: ''
title: 'NoobAshz'
description: 'Just another noobz on the net'
permalink: pretty
logo: "https://www.gravatar.com/avatar/a4adee4ab6f26d519302de965c03e4f1?s=52"
encoding: utf-8 # Make sure the encoding is right
lang: id-ID # Set the site language
email: "hi@ashz.xyz"
disqus: "ashz" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://www.gravatar.com/avatar/a4adee4ab6f26d519302de965c03e4f1" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference


# Pagination
paginate: 4
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: 3shoka # jekyll-seo-tag > Owners twitter username
author: Ashokani # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Ashokani # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/3shoka
    - https://www.facebook.com/3shoka
    - https://www.linkedin.com/in/3shoka
    - https://plus.google.com/+AshzShoka
    - https://github.com/3shoka

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/3shoka
  LinkedIn: https://www.linkedin.com/in/3shoka
  Google+: https://plus.google.com/+AshzShoka
  GitHub: https://github.com/3shoka
  # link: https://
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""